config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/login' => 'teams#login'
  resources :games
  resources :teams
  resources :members
  resources :participants
  root 'teams#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :team
    has_many :participants
    has_many :members, through: :participants
    accepts_nested_attributes_for :participants
end

app/models/makedgame.rb
class Makedgame < ApplicationRecord
    has_many :participants
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :team
    has_many :participants
    has_many :games, through: :participant
end

app/models/participant.rb
class Participant < ApplicationRecord
    belongs_to :member
    belongs_to :game
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :games
    has_many :members
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  private
  # 現在のユーザーを取得する
  # @_current_teamが空の場合は、session情報をキーにしてDBから検索する
  def current_team
    @_current_team ||= Team.find_by(id: session[:team_id])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

    def new
        @team = current_team()
    end
    
    def index
        @team = current_team()
        @games = Game.where(team_id: @team.id)
    end

    def show
        @game = Game.find_by(id: params[:id])
        # @game = Game.includes(:members, :participants).find_by(id: params[:id])
    end

    def create
        @team = current_team()
        @game = @team.games.create(
            date: params[:date],
            place: params[:place],
            opponent: params[:opponent],
            participation_flag: false
        )
        @game.save
        redirect_to('/games')
    end

    def edit
    end

    private
        def game_params
            params.require(:game).permit(:team_id, :date, :place, :opponent)
        end
    
    private
        def flag_to_mark(flag)
            case
            when flag then mark = '○'
            when !flag then mark = '×'
            end

            return mark
        end
    helper_method :flag_to_mark
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    def index
        @team = current_team
        @members = Member.where(team_id: @team.id)
    end

    def new
        @team = current_team
    end

    def create
        @team = current_team
        @member = @team.members.build(
            name:           params[:name], 
            skill_level:    params[:sl]
            )
        # games = Game.where(team_id: @team.id)
        # games.each do |game|
        #     part = @member.participants.build(
        #         game_id: game.id,
        #         participation_flag: false
        #     )
        # end
        @member.save
        redirect_to(members_path)
    end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

    def new
    end

    def index
        @participant = Participant.find_by(id: params[:id])
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    def index

    end

    def create
        @team = Team.new(
            name: params[:name]
        )
        @team.save
        session[:team_id] = @team.id
        redirect_to('/games')
    end

    def login
        session[:team_id] = params[:team_id]
        redirect_to('/games')
    end

    def new

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<h2>
    <%= @team.name %>'s Game Schedule List
</h2>
<p>
    <%= link_to('Add new schedule', new_game_path) %>
</p>
<p>
    <%= link_to('Show members', members_path) %>
</p>
<ul>
<% @games.each do |game| %>
<li>
<%= link_to '|||', game_path(game.id) %>
<%= game.date %> | <%= game.place %> | <%= game.opponent %>
</li>
<% end %>
</ul>

app/views/games/new.html.erb
<h2>
    New Schedule of <%= @team.name %>
</h2>
<%= form_tag(games_path) do %>
    <p>
        date<input type="date" name="date">
    </p>
    <p>
        place<input name="place">
    </p>
    <p>
        opponent<input name="opponent">
    </p>
    <p>
        <input type="submit" value="add">
    </p>
<% end %>

app/views/games/show.html.erb
<h2><%= @game.team.name %> VS <%= @game.opponent %> at <%= @game.place %></h2>
<h3><%= @game.date %></h3>
<%= link_to("[Edit]", edit_game_path) %>
<ul>
<% @game.members.each do |member| %>
<li>
<% part = member.participants.find_by(game_id: @game.id) %>
<%= member.name %>(SL<%= member.skill_level %>) |<%= flag_to_mark(part.participation_flag) %>| <%= part.comment %> <%= link_to('[edit]', participants_path(part.id)) %>
</li>
<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JpaScheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/members/index.html.erb
<h2>
    <%= @team.name %>'s Members List
</h2>
<p>
    <%= link_to('Add new member', new_member_path) %>
</p>
<ul>
<% @members.each do |member| %>
    <li>
        <%= link_to('|||', member_path(member.id)) %>
        <%= member.name %> | <%= member.skill_level %>
    </li>
<% end %>
</ul>

app/views/members/new.html.erb
<h2>
    Add new member into <%= @team.name %>!
</h2>
<%= form_tag(members_path) do %>
    <p>
        name<input name="name">
    </p>
    <p>
        skill_level<input name="sl">
    </p>
    <p>
        <input type="submit" value="add">
    </p>
<% end %>

app/views/participants/update.html.erb
<h2>Will you join this game?</h2>

<%= form_for @participant do |f| %>
<p>
<%= f.radio_button @participant, :participation_flag, '○' %>
</p>